### PR TITLE
fix device time

### LINKED ISSUE #121: use_device_time is broken

### PR DESCRIPTION
**Pull request by mikeferguson**
closes #121

### CODE REVIEW

File: openni2_camera/include/openni2_camera/openni2_device.h [hunk 1]
```diff
@@ -160,9 +160,6 @@ class OpenNI2Device
   bool depth_video_started_;
 
   bool image_registration_activated_;
-
-  bool use_device_time_;
```
Comment (mikeferguson) [inline openni2_camera/include/openni2_camera/openni2_device.h:164]: this is unused - removing it does break ABI - but these packages haven't even been synced out yet

File: openni2_camera/launch/camera_only.launch.py [hunk 2]
```diff
@@ -53,7 +53,7 @@ def generate_launch_description():
                     plugin='openni2_wrapper::OpenNI2Driver',
                     name='driver',
                     parameters=[{'depth_registration': True},
-                                {'use_device_time': False}],
+                                {'use_device_time': True}],
```
Comment (mikeferguson) [inline openni2_camera/launch/camera_only.launch.py:56]: this puts our example launch files more in line with ROS1 usage - where use_device_time was enabled by default

File: openni2_camera/src/openni2_frame_listener.cpp [hunk 3]
```diff
@@ -70,38 +72,38 @@ void OpenNI2FrameListener::onNewFrame(openni::VideoStream& stream)
...
     rclcpp::Time ros_now = node_->now();
 
-    if (!user_device_timer_)
+    if (!use_device_timer_)
     {
       image->header.stamp = ros_now;
 
-      RCLCPP_DEBUG(rclcpp::get_logger("openni2"), "Time interval between frames: %.4f ms", (float)((ros_now - prev_time_stamp_).nanoseconds() / 1e6));
+      RCLCPP_DEBUG(rclcpp::get_logger("openni2"), "Time interval between frames: %.4f ms",
+                   (float)((ros_now.nanoseconds() - prev_time_stamp_.nanoseconds()) / 1e6));
```
Comment (mikeferguson) [inline openni2_camera/src/openni2_frame_listener.cpp:80]: this needs to be X.nanoseconds() - Y.nanoseconds() because if you switch between use_device_time and not, you will get an std::runtime_error that the clock sources are different

**Comment by mikeferguson** [comment]
CI failure is only because of ABI change - which was expected due to fixing the name of a variable, and removing another unused one
